// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMhL97Fn2jK60BDdYb4G2qJVm-t1TX_yA',
    appId: '1:684467698659:web:962769f623f57c368abed6',
    messagingSenderId: '684467698659',
    projectId: 'travel-buddy-8cec7',
    authDomain: 'travel-buddy-8cec7.firebaseapp.com',
    storageBucket: 'travel-buddy-8cec7.appspot.com',
    measurementId: 'G-8P9B6DTLLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD38jV4LqvULmXGao-ESmlL3_ffALOteB0',
    appId: '1:684467698659:android:dcd37c6f35188e078abed6',
    messagingSenderId: '684467698659',
    projectId: 'travel-buddy-8cec7',
    storageBucket: 'travel-buddy-8cec7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF4n2OfiobFZzI4ajQ6SyUygO0hmhgOCE',
    appId: '1:684467698659:ios:d96628b25404ad278abed6',
    messagingSenderId: '684467698659',
    projectId: 'travel-buddy-8cec7',
    storageBucket: 'travel-buddy-8cec7.appspot.com',
    iosBundleId: 'com.example.travelBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF4n2OfiobFZzI4ajQ6SyUygO0hmhgOCE',
    appId: '1:684467698659:ios:d96628b25404ad278abed6',
    messagingSenderId: '684467698659',
    projectId: 'travel-buddy-8cec7',
    storageBucket: 'travel-buddy-8cec7.appspot.com',
    iosBundleId: 'com.example.travelBuddy',
  );
}
